name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  async: ^2.11.0
  camera: ^0.11.0+1
  camera_macos: ^0.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/